-- Add migration script here
CREATE TABLE tb_product
(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    create_time  DATETIME    NOT NULL DEFAULT '1000-01-01 00:00:00',
    deleted      INTEGER     NOT NULL DEFAULT 0,
    product_name VARCHAR(50) NOT NULL,
    description  VARCHAR(50),
    UNIQUE (product_name)
);
-- 属性表
CREATE TABLE tb_property
(
    property_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id    INTEGER     NOT NULL,
    identifier    TEXT        NOT NULL,
    property_name TEXT        NOT NULL,
    description   TEXT,
    data_schema   VARCHAR(50) NOT NULL,
    UNIQUE (product_id, identifier)
);

-- 服务表
CREATE TABLE tb_service
(
    service_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id   INTEGER NOT NULL,
    identifier   TEXT    NOT NULL,
    service_name TEXT    NOT NULL,
    service_type TEXT    NOT NULL,
    description  TEXT,
    properties   TEXT    NOT NULL,
    UNIQUE (product_id, identifier)
);

-- 服务和属性关联表,
CREATE TABLE tb_service_property
(
    service_id  INTEGER NOT NULL,
    property_id INTEGER NOT NULL,
    serial      INTEGER NOT NULL,
    FOREIGN KEY (service_id) REFERENCES tb_service (service_id),
    FOREIGN KEY (property_id) REFERENCES tb_property (property_id),
    UNIQUE (service_id, serial)
);

-- 计量单位表
CREATE TABLE tb_unit
(
    id               INTEGER PRIMARY KEY,
    unit             TEXT UNIQUE NOT NULL,
    unit_name        TEXT        NOT NULL,
    unit_description TEXT        NOT NULL
);
INSERT INTO tb_unit (id, unit, unit_name, unit_description)
VALUES (1, '', '无', '空单位'),
       (2, 'mm', '毫米', '毫米'),
       (3, 'cm', '厘米', '厘米'),
       (4, 'dm', '分米', '分米'),
       (5, 'km', '千米', '千米'),
       (6, 'm', '米', '米'),
       (7, 'c㎡', '平方厘米', '平方厘米'),
       (8, 'm㎡', '平方毫米', '平方毫米'),
       (9, 'k㎡', '平方千米', '平方千米'),
       (10, '㎡', '平方米', '平方米'),
       (11, 'nm', '纳米', '纳米'),
       (12, 'μm', '微米', '微米'),
       (13, 'L', '升', '升'),
       (14, 'mm³', '立方毫米', '立方毫米'),
       (15, 'cm³', '立方厘米', '立方厘米'),
       (16, 'km³', '立方千米', '立方千米'),
       (17, 'm³', '立方米', '立方米'),
       (18, 'h㎡', '公顷', '公顷'),
       (19, 'kPa', '千帕', '千帕'),
       (20, 'Pa', '帕斯卡', '帕斯卡'),
       (21, 'mg', '毫克', '毫克'),
       (22, 'g', '克', '克'),
       (23, 'kg', '千克', '千克'),
       (24, 'N', '牛', '牛'),
       (25, 'mL', '毫升', '毫升'),
       (26, '℉', '华氏度', '华氏度'),
       (27, 'K', '开尔文', '开尔文'),
       (28, 't', '吨', '吨'),
       (29, '°C', '摄氏度', '摄氏度'),
       (30, 'mPa', '毫帕', '毫帕'),
       (31, 'hPa', '百帕', '百帕'),
       (32, 'J', '焦耳', '焦耳'),
       (33, 'cal', '卡路里', '卡路里'),
       (34, 'kW·h', '千瓦时', '千瓦时'),
       (35, 'Wh', '瓦时', '瓦时'),
       (36, 'eV', '电子伏', '电子伏'),
       (37, 'kJ', '千焦', '千焦'),
       (38, '°', '度', '度'),
       (39, 'rad', '弧度', '弧度'),
       (40, 'Hz', '赫兹', '赫兹'),
       (41, 'μW', '微瓦', '微瓦'),
       (42, 'mW', '毫瓦', '毫瓦'),
       (43, 'kW', '千瓦特', '千瓦特'),
       (44, 'W', '瓦特', '瓦特'),
       (45, 'kn', '节', '节'),
       (46, 'km/h', '千米每小时', '千米每小时'),
       (47, 'm/s', '米每秒', '米每秒'),
       (48, '″', '秒', '秒'),
       (49, '′', '分', '分'),
       (50, 'min', '分钟', '分钟'),
       (51, 'h', '小时', '小时'),
       (52, 'day', '日', '日'),
       (53, 'week', '周', '周'),
       (54, 'month', '月', '月'),
       (55, 'year', '年', '年'),
       (56, 'kA', '千安', '千安'),
       (57, 'A', '安培', '安培'),
       (58, 'mV', '毫伏', '毫伏'),
       (59, 'V', '伏特', '伏特'),
       (60, 'ms', '毫秒', '毫秒'),
       (61, 's', '秒', '秒'),
       (62, 'nF', '纳法', '纳法'),
       (63, 'pF', '皮法', '皮法'),
       (64, 'μF', '微法', '微法'),
       (65, 'F', '法拉', '法拉'),
       (66, 'Ω', '欧姆', '欧姆'),
       (67, 'μA', '微安', '微安'),
       (68, 'mA', '毫安', '毫安'),
       (69, 'g/L', '克每升', '克每升'),
       (70, 'mg/L', '毫克每升', '毫克每升'),
       (71, 'μg/m³', '微克每立方米', '微克每立方米'),
       (72, 'mg/m³', '毫克每立方米', '毫克每立方米'),
       (73, 'g/m³', '克每立方米', '克每立方米'),
       (74, 'kg/m³', '千克每立方米', '千克每立方米'),
       (75, 'grav', '重力加速度', '重力加速度'),
       (76, 'dB', '分贝', '分贝'),
       (77, '%', '百分比', '百分比'),
       (78, 'lm', '流明', '流明'),
       (79, 'bit', '比特', '比特'),
       (80, 'g/mL', '克每毫升', '克每毫升'),
       (81, 'B', '字节', '字节'),
       (82, 'μg(d㎡·d)', '微克每平方分米每天', '微克每平方分米每天'),
       (83, 'ppm', '百万分率', '百万分率'),
       (84, 'pixel', '像素', '像素'),
       (85, 'Lux', '照度', '照度'),
       (86, 'KVar', '千乏', '千乏'),
       (87, 'μg/L', '微克每升', '微克每升'),
       (88, 'kcal', '千卡路里', '千卡路里'),
       (89, 'GB', '吉字节', '吉字节'),
       (90, 'MB', '兆字节', '兆字节'),
       (91, 'KB', '千字节', '千字节'),
       (92, 't/h', '吨每小时', '吨每小时'),
       (93, 'KCL/h', '千卡每小时', '千卡每小时'),
       (94, 'L/s', '升每秒', '升每秒'),
       (95, 'Mpa', '兆帕', '兆帕'),
       (96, 'm³/h', '立方米每小时', '立方米每小时'),
       (97, 'kvar/h', '千乏时', '千乏时'),
       (98, 'uw/cm2', '微瓦每平方厘米', '微瓦每平方厘米'),
       (99, '只', '只', '只'),
       (100, '%RH', '相对湿度', '相对湿度'),
       (101, 'm³/s', '立方米每秒', '立方米每秒'),
       (102, 'kg/s', '公斤每秒', '公斤每秒'),
       (103, 'r/min', '转每分钟', '转每分钟'),
       (104, 'count', '次', '次'),
       (105, 'gear', '档', '档'),
       (106, 'stepCount', '步', '步'),
       (107, 'Nm3/h', '标准立方米每小时', '标准立方米每小时'),
       (108, 'kV', '千伏', '千伏'),
       (109, 'KVA', '千伏安', '千伏安'),
       (110, 'kvar', '千乏', '千乏'),
       (111, 'turn/m', '转每分钟', '转每分钟'),
       (112, 'V/m', '伏特每米', '伏特每米'),
       (113, 'ml/min', '滴速', '滴速'),
       (114, 'mm/Hg', '血压', '血压'),
       (115, 'mmol/L', '血糖', '血糖'),
       (116, 'mm/s', '毫米每秒', '毫米每秒'),
       (117, 'N/C', '牛顿每库仑', '牛顿每库仑'),
       (118, 'ppb', '微克每升', '微克每升'),
       (119, 'uS/cm', '微西每厘米', '微西每厘米'),
       (120, 'ppt', '纳克每升', '纳克每升');




